package salespersonsApplication;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Joel
 */
public class Home extends javax.swing.JFrame {

    //declarations
    private ArrayList<Salesperson> salespersonsList = new ArrayList();
    private int salespersonsCounter = 0;
    private DefaultTableModel listModel;
    private DefaultTableModel figuresModel;

    //side panel colors
    private Color selectedPanelColor = new Color(77, 19, 209);
    private Color unselectedPanelColor = new Color(58, 83, 155);

    /**
     * Creates new form MainPage
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        readSalespersonsFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        sidePanelList = new javax.swing.JPanel();
        salespersonsListLabel = new javax.swing.JLabel();
        sidePanelAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sidePanelFigures = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidePanelDelete = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sidePanelUpdate = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        salespersonsListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salespersonsListTable = new javax.swing.JTable();
        listPanelHeading = new javax.swing.JLabel();
        salesFiguresPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        salesFiguresTable = new javax.swing.JTable();
        figuresPanelHeading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        sidePanelList.setBackground(new java.awt.Color(77, 19, 209));
        sidePanelList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sidePanelList.setForeground(new java.awt.Color(255, 255, 255));

        salespersonsListLabel.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        salespersonsListLabel.setForeground(new java.awt.Color(255, 255, 255));
        salespersonsListLabel.setText("Salesperson List");
        salespersonsListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salespersonsListLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelListLayout = new javax.swing.GroupLayout(sidePanelList);
        sidePanelList.setLayout(sidePanelListLayout);
        sidePanelListLayout.setHorizontalGroup(
            sidePanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelListLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(salespersonsListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelListLayout.setVerticalGroup(
            sidePanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salespersonsListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePanelAdd.setBackground(new java.awt.Color(58, 83, 155));
        sidePanelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sidePanelAdd.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelAddMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Salesperson");

        javax.swing.GroupLayout sidePanelAddLayout = new javax.swing.GroupLayout(sidePanelAdd);
        sidePanelAdd.setLayout(sidePanelAddLayout);
        sidePanelAddLayout.setHorizontalGroup(
            sidePanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelAddLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelAddLayout.setVerticalGroup(
            sidePanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanelFigures.setBackground(new java.awt.Color(58, 83, 155));
        sidePanelFigures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sidePanelFigures.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelFigures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelFiguresMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sales Figures");

        javax.swing.GroupLayout sidePanelFiguresLayout = new javax.swing.GroupLayout(sidePanelFigures);
        sidePanelFigures.setLayout(sidePanelFiguresLayout);
        sidePanelFiguresLayout.setHorizontalGroup(
            sidePanelFiguresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelFiguresLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelFiguresLayout.setVerticalGroup(
            sidePanelFiguresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelFiguresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanelDelete.setBackground(new java.awt.Color(58, 83, 155));
        sidePanelDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sidePanelDelete.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelDeleteMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete Salesperson");

        javax.swing.GroupLayout sidePanelDeleteLayout = new javax.swing.GroupLayout(sidePanelDelete);
        sidePanelDelete.setLayout(sidePanelDeleteLayout);
        sidePanelDeleteLayout.setHorizontalGroup(
            sidePanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelDeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelDeleteLayout.setVerticalGroup(
            sidePanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelDeleteLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        sidePanelUpdate.setBackground(new java.awt.Color(58, 83, 155));
        sidePanelUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sidePanelUpdate.setForeground(new java.awt.Color(255, 255, 255));
        sidePanelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidePanelUpdateMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update Salespersons Info");

        javax.swing.GroupLayout sidePanelUpdateLayout = new javax.swing.GroupLayout(sidePanelUpdate);
        sidePanelUpdate.setLayout(sidePanelUpdateLayout);
        sidePanelUpdateLayout.setHorizontalGroup(
            sidePanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelUpdateLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelUpdateLayout.setVerticalGroup(
            sidePanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Log out");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salespersonsApplication/images/icons8_Male_User_50px.png"))); // NOI18N
        jLabel11.setText("  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanelDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanelFigures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(sidePanelList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanelFigures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salespersons Management System");

        minLabel.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        minLabel.setForeground(new java.awt.Color(255, 255, 255));
        minLabel.setText("-");
        minLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLabelMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(minLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        salespersonsListPanel.setBackground(new java.awt.Color(255, 255, 255));

        salespersonsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Number", "Firsrt Name", "Last Name", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salespersonsListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(salespersonsListTable);

        listPanelHeading.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        listPanelHeading.setText("Salespersons List");

        javax.swing.GroupLayout salespersonsListPanelLayout = new javax.swing.GroupLayout(salespersonsListPanel);
        salespersonsListPanel.setLayout(salespersonsListPanelLayout);
        salespersonsListPanelLayout.setHorizontalGroup(
            salespersonsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salespersonsListPanelLayout.createSequentialGroup()
                .addComponent(listPanelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        salespersonsListPanelLayout.setVerticalGroup(
            salespersonsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salespersonsListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listPanelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLayeredPane1.add(salespersonsListPanel, "card3");

        salesFiguresPanel.setBackground(new java.awt.Color(255, 255, 255));

        salesFiguresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Number", "Last Name", "Sales Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salesFiguresTable.setColumnSelectionAllowed(true);
        salesFiguresTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(salesFiguresTable);
        salesFiguresTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        figuresPanelHeading.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        figuresPanelHeading.setText("Salespersons List");

        javax.swing.GroupLayout salesFiguresPanelLayout = new javax.swing.GroupLayout(salesFiguresPanel);
        salesFiguresPanel.setLayout(salesFiguresPanelLayout);
        salesFiguresPanelLayout.setHorizontalGroup(
            salesFiguresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesFiguresPanelLayout.createSequentialGroup()
                .addComponent(figuresPanelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        salesFiguresPanelLayout.setVerticalGroup(
            salesFiguresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesFiguresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(figuresPanelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLayeredPane1.add(salesFiguresPanel, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(237, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Loads data from file into the array, list and figures table
     */
    private void readSalespersonsFile() {

        //declarations
        int ID;
        String firstName;
        String lastName;
        String telephone;
        double salesAmount;
        String line;
        String[] fields;

        //default table model assignment 
        listModel = (DefaultTableModel) salespersonsListTable.getModel();
        figuresModel = (DefaultTableModel) salesFiguresTable.getModel();

        try {
            //File objects declarations
            FileReader file = new FileReader("SalespersonsList.txt");
            BufferedReader reader = new BufferedReader(file);

            line = reader.readLine();
            while (line != null) {

                //assign salesperson's fields
                fields = line.split(",");
                ID = Integer.parseInt(fields[0].trim());
                firstName = fields[1].trim();
                lastName = fields[2].trim();
                if (isTelephoneFormatted(fields[3].trim())) {
                    telephone = fields[3].trim();
                } else {
                    telephone = formatTelephone(fields[3].trim());
                }
                salesAmount = Double.parseDouble(fields[4].trim());

                //populate ArrayList, salesperson list and sales figures tables
                salespersonsList.add(new Salesperson(ID, firstName, lastName, telephone, salesAmount));
                checkTablesListCount();

                //set salesperons list table row
                setRow(salespersonsCounter, ID, firstName, lastName, telephone);

                //set sales figures table row
                setRow(salespersonsCounter, ID, lastName, salesAmount);

                ++salespersonsCounter;
                line = reader.readLine();

            }
            salespersonsListTable.setModel(listModel);
            salesFiguresTable.setModel(figuresModel);

            reader.close();

        } catch (IOException error) {

            JOptionPane.showMessageDialog(null, error.getMessage());
        }

    }


    private void minLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLabelMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minLabelMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //declaration
        int confirmation;

        confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit the program?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            writeToFile();
            System.exit(0);

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void salespersonsListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salespersonsListLabelMouseClicked

        //Set Side Panel Color 
        sidePanelList.setBackground(selectedPanelColor);
        sidePanelAdd.setBackground(unselectedPanelColor);
        sidePanelFigures.setBackground(unselectedPanelColor);
        sidePanelDelete.setBackground(unselectedPanelColor);
        sidePanelUpdate.setBackground(unselectedPanelColor);

        //set main main screen subheading label and switch layered pane panel
        listPanelHeading.setText("Salespersons List");
        jLayeredPane1.removeAll();
        jLayeredPane1.add(salespersonsListPanel);
        this.repaint();
        this.revalidate();

    }//GEN-LAST:event_salespersonsListLabelMouseClicked

    private void sidePanelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelAddMouseClicked

        //set sided panel color
        sidePanelAdd.setBackground(selectedPanelColor);
        sidePanelList.setBackground(unselectedPanelColor);
        sidePanelFigures.setBackground(unselectedPanelColor);
        sidePanelDelete.setBackground(unselectedPanelColor);
        sidePanelUpdate.setBackground(unselectedPanelColor);

        AddSalespersonForm add = new AddSalespersonForm(this);
        add.setVisible(true);
    }//GEN-LAST:event_sidePanelAddMouseClicked

    private void sidePanelFiguresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelFiguresMouseClicked

        //set Panel Color
        sidePanelFigures.setBackground(selectedPanelColor);
        sidePanelAdd.setBackground(unselectedPanelColor);
        sidePanelDelete.setBackground(unselectedPanelColor);
        sidePanelList.setBackground(unselectedPanelColor);
        sidePanelUpdate.setBackground(unselectedPanelColor);

        //set main main screen subheading label and switch layered pane panel
        figuresPanelHeading.setText("Sales Figures");
        jLayeredPane1.removeAll();
        jLayeredPane1.add(salesFiguresPanel);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_sidePanelFiguresMouseClicked

    private void sidePanelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelDeleteMouseClicked

        //set panel color
        sidePanelDelete.setBackground(selectedPanelColor);
        sidePanelAdd.setBackground(unselectedPanelColor);
        sidePanelFigures.setBackground(unselectedPanelColor);
        sidePanelList.setBackground(unselectedPanelColor);
        sidePanelUpdate.setBackground(unselectedPanelColor);
    }//GEN-LAST:event_sidePanelDeleteMouseClicked

    private void sidePanelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelUpdateMouseClicked

        //set panel Color
        sidePanelUpdate.setBackground(selectedPanelColor);
        sidePanelAdd.setBackground(unselectedPanelColor);
        sidePanelList.setBackground(unselectedPanelColor);
        sidePanelDelete.setBackground(unselectedPanelColor);
        sidePanelFigures.setBackground(unselectedPanelColor);
    }//GEN-LAST:event_sidePanelUpdateMouseClicked

    public ArrayList<Salesperson> getSalespersonsList() {
        return salespersonsList;
    }

    public boolean isTelephoneFormatted(String telephone) {

        //declaration
        boolean formatted = false;
        int digitsNumber = 15;

        if (telephone.length() == digitsNumber) {
            if (telephone.charAt(3) == ' ' && telephone.charAt(6) == ' ' && telephone.charAt(10) == ' ') {
                formatted = true;
            }

        }
        return formatted;

    }

    public String formatTelephone(String number) {

        //declaration
        StringBuilder phone = new StringBuilder(number);

        phone.insert(3, " ");
        phone.insert(6, " ");
        phone.insert(10, " ");

        return phone.toString();
    }

    public void checkTablesListCount() {
        if (salespersonsListTable.getRowCount() == getSalespersonsList().size() - 1) {
            figuresModel.setRowCount(getSalespersonsList().size() + 5);
            listModel.setRowCount(getSalespersonsList().size() + 5);

        }
    }

    public void addRecord(String firstName, String lastName, String telephone, double salesAmount) {
        int ID = generateID();
        salespersonsList.add(new Salesperson(ID, firstName, lastName, telephone, salesAmount));
        checkTablesListCount();
        setRow(salespersonsCounter, ID, firstName, lastName, telephone);
        setRow(salespersonsCounter, ID, lastName, salesAmount);
        salespersonsListTable.setModel(listModel);
        salesFiguresTable.setModel(figuresModel);
        ++salespersonsCounter;
    }

    public int generateID() {

        return salespersonsList.get(salespersonsList.size() - 1).getID() + 1;
    }

    public void setRow(int row, int ID, String firstName, String lastName, String telephone) {
        listModel.setValueAt(ID, row, 0);
        listModel.setValueAt(firstName, row, 1);
        listModel.setValueAt(lastName, row, 2);
        listModel.setValueAt(telephone, row, 3);

    }

    public void setRow(int row, int ID, String lastName, double salesAmount) {

        figuresModel.setValueAt(ID, row, 0);
        figuresModel.setValueAt(lastName, row, 1);
        figuresModel.setValueAt(salesAmount, row, 2);
    }

    /**
     * Returns the subsequent ID number in the list
     *
     */
    public void writeToFile() {

        try {
            //File objects
            FileWriter file = new FileWriter("SalespersonsList.txt");
            BufferedWriter writer = new BufferedWriter(file);

            //variable declarations
            String line = "";
            String separator = ",";
            int ID;
            String firstName;
            String lastName;
            String telephone;
            double salesAmount;

            for (int index = 0; index < salespersonsList.size(); index++) {
                ID = salespersonsList.get(index).getID();
                firstName = salespersonsList.get(index).getFirstName();
                lastName = salespersonsList.get(index).getLastName();
                telephone = salespersonsList.get(index).getTelephone();
                salesAmount = salespersonsList.get(index).getSalesAmount();
                line = ID + separator + firstName + separator + lastName + separator + telephone + separator + salesAmount;
                writer.write(line, 0, line.length());
                writer.newLine();
            }

            writer.close();
        } catch (IOException error) {
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel figuresPanelHeading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel listPanelHeading;
    private javax.swing.JLabel minLabel;
    private javax.swing.JPanel salesFiguresPanel;
    private javax.swing.JTable salesFiguresTable;
    private javax.swing.JLabel salespersonsListLabel;
    private javax.swing.JPanel salespersonsListPanel;
    private javax.swing.JTable salespersonsListTable;
    private javax.swing.JPanel sidePanelAdd;
    private javax.swing.JPanel sidePanelDelete;
    private javax.swing.JPanel sidePanelFigures;
    private javax.swing.JPanel sidePanelList;
    private javax.swing.JPanel sidePanelUpdate;
    // End of variables declaration//GEN-END:variables

}
